# Generated by Django 5.0.6 on 2024-05-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='someobject',
            name='Created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='someobject',
            name='Modified',
            field=models.DateTimeField(null=True),
        ),
    ]
